// Code generated by protoc-gen-joymicro. DO NOT EDIT.
// source: api.desc/hello.proto

package proto1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "joynova.com/joynova/joymicro/client"
	server "joynova.com/joynova/joymicro/service"
	"time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

var serviceName = "hello"

type HelloServiceInterface interface {
	Hello(context.Context, *Request) (*Response, error)
	HelloAll(context.Context, *Request) (*Response, error)
}

func NewHelloService(etcdAddrs []string, timeout time.Duration, isPermanent bool) HelloServiceInterface {
	c := client.New(serviceName+"/"+serviceName, etcdAddrs, timeout, isPermanent)
	return &helloService{
		c: c,
	}
}

type helloService struct {
	c *client.Service
}

func (c *helloService) Hello(ctx context.Context, in *Request) (*Response, error) {
	out := new(Response)
	err := c.c.Call(ctx, "Hello", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloService) HelloAll(ctx context.Context, in *Request) (*Response, error) {
	out := new(Response)
	err := c.c.CallAll(ctx, "Hello", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type HelloHandlerInterface interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterHelloHandler(s *server.ServicesManager, hdlr HelloHandlerInterface) error {
	return s.RegisterOneService(serviceName+"/"+serviceName, hdlr)
}
